plugins:
  feature_voting_enabled:
    default: true
    client: true
  feature_voting_vote_limit:
    default: 10
    client: true
  feature_voting_super_vote_limit:
    default: 3
    client: true
  feature_voting_show_who_voted:
    default: true
    client: true